apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  name: enable-alerts-
  labels:
    codefresh.io/cert: enable-job  
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
